<a href="https://colab.research.google.com/github/daniivelascoo/ifp-programacion-ia/blob/main/Teoria_1_2_B_Dimensiones_Slicing_Student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🧠 Teoría Bloque B: El Mundo Multidimensional
**Sprint 1.2 - NumPy & Lógica Vectorial**

En Ciencia de Datos, raramente trabajamos con una sola fila de números.
*   Una hoja de Excel es **2D** (Filas y Columnas).
*   Una foto en blanco y negro es **2D** (Alto y Ancho).
*   Un vídeo es **4D** (Tiempo, Alto, Ancho, Color).

Hoy aprenderás a navegar por estas dimensiones usando `.shape` y **Slicing**.

### 🎯 Objetivos:
1.  **Forma (Shape):** Entender las dimensiones de una matriz.
2.  **Slicing 2D:** Recortar trozos de una matriz (Filas y Columnas).
3.  **Reshape:** Cambiar la forma de los datos sin cambiar su contenido.

## 1. Creando Matrices (2D)

Para crear una matriz, anidamos listas dentro de listas.
Visualmente:
*   Eje 0 = Filas (Bajar).
*   Eje 1 = Columnas (Avanzar).

In [1]:
import numpy as np

# Creamos una matriz 3x3 (3 filas, 3 columnas)
matriz = np.array([
    [10, 20, 30],  # Fila 0
    [40, 50, 60],  # Fila 1
    [70, 80, 90]   # Fila 2
])

print("Matriz completa:\n", matriz)

# 1. DIMENSIONES (.ndim)
# ¿Cuántos ejes tiene? (Si es una tabla, serán 2)
print(f"Dimensiones: {matriz.ndim}") # TODO: Usa el atributo ndim

# 2. FORMA (.shape)
# ¿Cuántas filas y columnas tiene? (Devuelve una tupla)
forma = matriz.shape # TODO: Usa el atributo shape
print(f"Forma (Filas, Columnas): {forma}")

# PISTA:
# En IA, si te sale un error de "Shape Mismatch", mira siempre esto.

Matriz completa:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimensiones: 2
Forma (Filas, Columnas): (3, 3)


## 2. Slicing Avanzado (Recortando datos)

En Python normal accederías así: `lista[fila][columna]`.
En NumPy usamos una sintaxis más potente con una sola coma: `matriz[fila, columna]`.

El operador clave es los dos puntos `:`. Significa **"Todo"** o **"Desde:Hasta"**.

In [2]:
# Usamos la misma matriz de antes:
# [[10, 20, 30],
#  [40, 50, 60],
#  [70, 80, 90]]

# 1. ELEMENTO ÚNICO
# Queremos el 50 (Fila 1, Columna 1)
centro = matriz[1, 1] # TODO: Pon el índice de la columna
print(f"Centro: {centro}")

# 2. FILA COMPLETA
# Queremos toda la primera fila (Fila 0)
# Sintaxis: [fila_fija, todas_las_columnas]
fila_cero = matriz[0, :]
print(f"Primera fila: {fila_cero}")

# 3. COLUMNA COMPLETA (Esto no se puede hacer fácil en Python normal)
# Queremos la última columna (30, 60, 90) -> Índice 2
# Sintaxis: [todas_las_filas, columna_fija]
columna_final = matriz[:, 2] # TODO: Usa ':' para seleccionar todas las filas
print(f"Columna final: {columna_final}")

# 4. SUB-MATRIZ (Recorte cuadrado)
# Queremos el cuadrado superior derecho [[20, 30], [50, 60]]
# Filas: de la 0 a la 2 (excluido). Columnas: de la 1 a la 3 (excluido).
cuadrado = matriz[0:2, 1:3]
print(f"Recorte:\n{cuadrado}")

Centro: 50
Primera fila: [10 20 30]
Columna final: [30 60 90]
Recorte:
[[20 30]
 [50 60]]


## 3. Reshape (Transformación)

A veces la IA necesita que le demos los datos "aplanados" (1D) y a veces como "imagen" (2D). `reshape` cambia la forma pero mantiene los datos.

**Regla de Oro:** El número total de elementos debe mantenerse.
(Si tienes 12 datos, puedes hacer 3x4 o 6x2, pero no 3x3).

In [3]:
# Creamos un vector simple de 12 números
vector = np.arange(1, 13)
print(f"Vector original (1D): {vector}")

# 1. CONVERTIR A MATRIZ (3 Filas x 4 Columnas)
# 3 * 4 = 12, así que es válido.
matriz_3x4 = vector.reshape(3, 4) # TODO: Pon las dimensiones 3, 4
print(f"\nMatriz 3x4:\n{matriz_3x4}")

# 2. CONVERTIR A MATRIZ (6 Filas x 2 Columnas)
matriz_6x2 = vector.reshape(6, 2)
print(f"\nMatriz 6x2:\n{matriz_6x2}")

# 3. APLANAR (Flattening)
# Volvemos a convertir la matriz 3x4 en una línea larga.
# Usamos -1 para decirle a NumPy "calcula tú esta dimensión".
aplanado = matriz_3x4.reshape(-1)
print(f"\nAplanado de nuevo: {aplanado}")

Vector original (1D): [ 1  2  3  4  5  6  7  8  9 10 11 12]

Matriz 3x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matriz 6x2:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

Aplanado de nuevo: [ 1  2  3  4  5  6  7  8  9 10 11 12]
