<a href="https://colab.research.google.com/github/daniivelascoo/ifp-programacion-ia/blob/main/Teoria_1_2_C_Math_Broadcasting_Student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🧠 Teoría Bloque C: Matemáticas y Filtros Mágicos
**Sprint 1.2 - NumPy & Lógica Vectorial**

Ya sabes crear matrices y recortarlas. Ahora vamos a **operar** con ellas.
NumPy nos permite sumar, restar o comparar millones de datos sin escribir un solo bucle `for`.

### 🎯 Objetivos:
1.  **Operaciones Element-Wise:** Sumar matrices como si fueran números simples.
2.  **Broadcasting:** La magia de NumPy para operar matrices de distintos tamaños.
3.  **Máscaras Booleanas:** Filtrar datos usando preguntas lógicas (`datos > 0`).

## 1. Operaciones Element-Wise (Elemento a Elemento)

Si tienes dos matrices del mismo tamaño, las operaciones (`+`, `-`, `*`, `/`) se aplican a cada pareja de números en la misma posición.

In [1]:
import numpy as np

# Creamos dos matrices 2x2
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[10, 20],
              [30, 40]])

print(f"Matriz A:\n{A}")
print(f"Matriz B:\n{B}")

# 1. SUMA DIRECTA
# No hace falta bucle. Suma el 1 con el 10, el 2 con el 20...
suma = A + B
print(f"\nSuma (A + B):\n{suma}")

# 2. MULTIPLICACIÓN POR ESCALAR
# Multiplicamos toda la matriz A por 10
escalado = A * 10 # TODO: Multiplica por 10
print(f"\nEscalado (A * 10):\n{escalado}")

# 3. CUADRADO
# Elevamos cada número al cuadrado
cuadrado = A ** 2 # TODO: Eleva a la potencia de 2
print(f"\nCuadrado (A^2):\n{cuadrado}")

Matriz A:
[[1 2]
 [3 4]]
Matriz B:
[[10 20]
 [30 40]]

Suma (A + B):
[[11 22]
 [33 44]]

Escalado (A * 10):
[[10 20]
 [30 40]]

Cuadrado (A^2):
[[ 1  4]
 [ 9 16]]


## 2. Broadcasting (La Magia de NumPy)

¿Qué pasa si intentas sumar una Matriz (2D) y un Vector (1D)?
En matemáticas clásicas: **Error**.
En NumPy: **Broadcasting**.

NumPy "estira" automáticamente el vector pequeño para que coincida con el grande.

In [2]:
# Tenemos una matriz de (3 filas x 3 columnas)
matriz = np.array([
    [1, 1, 1],
    [1, 1, 1],
    [1, 1, 1]
])

# Tenemos un vector fila (1 fila, 3 columnas)
fila = np.array([0, 10, 20])

print(f"Matriz shape: {matriz.shape}")
print(f"Fila shape:   {fila.shape}")

# INTENTO DE SUMA
# NumPy va a coger la 'fila' y la va a repetir en cada fila de la matriz
resultado = matriz + fila # TODO: Suma la variable 'fila'
print(f"\nResultado Broadcasting:\n{resultado}")

# Fíjate: Ha sumado 0 a la primera columna, 10 a la segunda y 20 a la tercera.
# ¡En todas las filas a la vez!

Matriz shape: (3, 3)
Fila shape:   (3,)

Resultado Broadcasting:
[[ 1 11 21]
 [ 1 11 21]
 [ 1 11 21]]


## 3. Máscaras Booleanas (Filtros Lógicos)

Esta es la herramienta más usada en Ciencia de Datos para limpiar valores.
En lugar de decir *"Dame la fila 3"*, decimos *"Dame los datos que sean mayores que 0"*.

1.  Creamos una **Pregunta** (`data > 0`) -> Devuelve `True`/`False`.
2.  Usamos esa respuesta como **Índice** -> Devuelve los datos.

In [4]:
# Datos de temperatura (algunos son errores, -999)
datos = np.array([25, 30, -999, 28, -999, 32])

# PASO 1: LA MÁSCARA (La Pregunta)
# ¿Qué datos son válidos (mayores que -100)?
# Esto crea un array de Booleanos (True/False)
mascara = datos > -100 # TODO: Pon la condición (-100)

print(f"Datos originales: {datos}")
print(f"Máscara lógica:   {mascara}")

# PASO 2: EL FILTRADO (Aplicar la máscara)
# NumPy solo deja pasar los que son True
datos_limpios = datos[mascara] # TODO: Pon la variable 'mascara' dentro de los corchetes

print(f"Datos limpios:    {datos_limpios}")

# BONUS: ¿Cuántos datos válidos tenemos?
# En Python, True cuenta como 1 y False como 0.
conteo = np.sum(mascara)
print(f"Número de lecturas válidas: {conteo}")

Datos originales: [  25   30 -999   28 -999   32]
Máscara lógica:   [ True  True False  True False  True]
Datos limpios:    [25 30 28 32]
Número de lecturas válidas: 4
